### ISSUE TITLE
Getting Error while Adding Repo

### ISSUE THREAD

**Issue by MxBln** [unifi-blueberry/addon-podman#12]
Hi,

I am getting following error and Stuck on step one: 
```

root@Primalsource:~# gpg --no-default-keyring \
>   --keyring /usr/share/keyrings/unifi-blueberry.gpg \
>   --keyserver keyserver.ubuntu.com \
>   --recv-keys C320FD3D3BF10DA7415B29F700CCEE392D0CA761
gpg: failed to create temporary file '/root/.gnupg/.#lk0x00000055946e86f0.Primalsource.25933': No such file or directory
gpg: connecting dirmngr at '/root/.gnupg/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr
```

What can I do about it? 

I am running a UDM-Base and FW:2.4

BR
Max

**Comment by zlangbert** [comment]
Thanks for the report! I was able to reproduce in a `debian:stretch` container. 

Looks like this happens if the `~/.gnupg` directory doesn't exist. `gpg` can be initialized by running `gpg --list-keys`, which will create the required directory.

Updated the docs in #13 to reflect this.
